# Generated by Django 4.1.7 on 2023-02-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
