# Generated by Django 4.1.7 on 2023-03-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_shippingaddress_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_num',
        ),
    ]
