# Generated by Django 4.1.7 on 2023-03-06 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_managers'),
        ('store', '0009_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('cmnd', models.CharField(max_length=12, unique=True)),
                ('address', models.CharField(max_length=511)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
