# Generated by Django 4.1.7 on 2023-03-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='staff',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='employment_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
