# Generated by Django 4.1.7 on 2023-03-07 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_shippingaddress_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSDCKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.shippingaddress')),
                ('cus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
            ],
            options={
                'unique_together': {('cus_id', 'add_id')},
            },
        ),
    ]
