# Generated by Django 4.1.7 on 2023-03-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_customer_email_alter_customer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
