# Generated by Django 4.1.7 on 2023-03-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arthur',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
