# Generated by Django 4.1.7 on 2023-03-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
