# Generated by Django 4.1.7 on 2023-03-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='responded',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
